services:
    php:
        build:
            context: .
        volumes:
            - ./:/var/www/html

    web:
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    node:
        image: node:22
        user: node
        working_dir: /assets
        ports:
            - 5173:5173
        volumes:
            -   ./:/assets
        command: npm run dev

    db:
        image: mariadb:11.5.2
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - mysqldata:/var/lib/mysql

    redis:
        image: redis:7.4
        volumes:
            - redisdata:/data

volumes:
    mysqldata:
    redisdata:
